build:
  system_packages:
    - "ffmpeg"
    - "libsm6"
    - "libxext6"
  python_packages:
    - "accelerate==0.21.0"
    - "datasets==2.14.0"
    - "diffusers==0.18.2"
    - "Pillow==10.0.0"
    - "torch==2.0.1"
    - "transformers==4.31.0"
    - "triton==2.0.0"
    - "xformers==0.0.20"
    - "wandb==0.15.5"
  